jaconi:
  rabbitmq:
    listener:
      retry:
        # Enable or disable the retry functionality entirely.
        enabled: true

        # Create the RabbitMQ resources (exchanges and queues) automatically.
        create-resources: true

        # Configure the source queues. Messages from these queues will be retried.
        queues: [ ]
           # Messages originating from a queue named com.example.exchange will be retried.
           # "[com.example.queue]":
           # A message will be retried 5 times before being sent to a DLX or discarded.
           #   max-attempts: 5
           #   durations:
           # The first attempt will happen after 10 Seconds.
           #     - 10s
           # The second attempt will happen after another 15 Seconds.
           #     - 15s
           # The third attempt will happen after another 30 Seconds. All subsequent attempts (up to max-attempts) will
           # happen another 30 seconds after the previous attempt.
           #     - 30s
