name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v5
        with:
          # We need ${{github.event.pull_request.commits}} + 1 commits.
          fetch-depth: 0
          token: ${{ github.token }}

      - uses: actions/setup-node@v5
        with:
          node-version: lts/*

      - name: Lint commit message(s)
        run: |
          yarn add @commitlint/cli
          yarn add @commitlint/config-conventional
          yarn run commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose

  test:
    permissions:
      checks: write
      contents: read

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v5
        with:
          java-version: '17'
          distribution: 'temurin'

      - uses: gradle/actions/wrapper-validation@v4

      - uses: gradle/actions/setup-gradle@v4

      - name: Run Tests
        run: ./gradlew test

      - name: JUnit Report
        if: always() # always run even if the previous step fails
        uses: mikepenz/action-junit-report@v5
        with:
          report_paths: 'build/test-results/*/*.xml'

  release:
    needs:
      - lint
      - test
    # Workaround to make release run even though lint didn't (which is the case for a PR merge to main)
    # See: https://stackoverflow.com/questions/68945610/how-to-put-conditional-job-in-need-of-another-job-in-github-action
    if: |
      always() &&
      github.event_name == 'push' &&
      (needs.lint.result == 'success' || needs.lint.result == 'skipped') && 
      needs.test.result == 'success'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          # Use a different token so subsequent workflows are executed.
          # See https://github.community/t/action-does-not-trigger-another-on-push-tag-action/17148
          token: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          fetch-depth: 0

      - uses: cycjimmy/semantic-release-action@v5
        with:
          extra_plugins: |
            @semantic-release/exec
            @semantic-release/git
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_GITHUB_TOKEN }}
          GITHUB_REPO: ${{ github.repository }}
