name: Lint Commits

on:
  pull_request:
    branches:
      - main

jobs:
  lint-commits:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Lint commit message(s)
        run: |
          yarn add @commitlint/cli
          yarn add @commitlint/config-conventional
          yarn run commitlint --from HEAD~${{ github.event.pull_request.commits }} --to HEAD
